version: 2

references:
  default_setup: &default_setup
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/guessi/kubectl-search

  filter_master_or_tag: &filter_master_or_tag
    filters:
      tags:
        only:
          - /^v[0-9]+\.[0-9]+\.[0-9]+/
      branches:
        only: master

  filter_tag_only: &filter_tag_only
    filters:
      tags:
        only:
          - /^v[0-9]+\.[0-9]+\.[0-9]+/
      branches:
        ignore: /.*/

jobs:
  bootstrap:
    <<: *default_setup
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: make bootstrap
      - run:
          name: Code Lint
          command: make lint
      - run:
          name: Setup Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            go fmt ./...
            go vet ./...
            # go test -v ./...
      - save_cache:
          key: v1-kubectl-search-{{ checksum "go.mod" }}-source
          paths:
            - /go/pkg/mod
  build:
    <<: *default_setup
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-kubectl-search-{{ checksum "go.mod" }}-source
      - run:
          name: Build Code
          command: make
      - save_cache:
          key: v1-kubectl-search-{{ .Environment.CIRCLE_SHA1 }}-workspace
          paths:
            - /go/src/github.com/guessi/kubectl-search
  release:
    <<: *default_setup
    steps:
      - restore_cache:
          keys:
            - v1-kubectl-search-{{ .Environment.CIRCLE_SHA1 }}-workspace
      - run:
          name: Release
          command: make release

workflows:
  version: 2
  main-workflow:
    jobs:
      - bootstrap:
          <<: *filter_master_or_tag
      - build:
          requires:
            - bootstrap
          <<: *filter_master_or_tag
      - release:
          requires:
            - build
          <<: *filter_tag_only
